### ISSUE TITLE
Training error！

### ISSUE THREAD

**Issue by XLR-man** [lifuguan/GGRt_official#6]
In your paper, a 3090 GPU is needed. but when i train in a 4090 GPU, it was cuda out of memory:
```
[INFO] Outputs will be saved to ./data/ibrnet/train/out/pretrain_llff
Training pretrain_llff:   0%|                                                                                                  | 0/6000 [00:00<?, ?it/s][INFO] Resuming from latest checkpoint...
[WARNING] Checkpoint ./data/ibrnet/train/out/pretrain_llff/model.pth does not exist, training from scratch!
train set len 2785
176 240
Error executing job with overrides: []
Traceback (most recent call last):
  File "/data/xielangren/project/GGRt_official/train_ggrt_stable.py", line 333, in train
    trainer.train()
  File "/data/xielangren/project/GGRt_official/ggrt/base/trainer.py", line 224, in train
    self.train_iteration(data_batch=self.train_data)
  File "/data/xielangren/project/GGRt_official/train_ggrt_stable.py", line 109, in train_iteration
    ret, data_gt = self.model.gaussian_model(batch, self.iteration)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xielangren/project/GGRt_official/ggrt/model/pixelsplat/pixelsplat.py", line 190, in forward
    tmp_gaussians = self.encoder(tmp_batch, global_step,None,i,j, crop_size,True)   # 计算当前帧的gaussian
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xielangren/project/GGRt_official/ggrt/model/pixelsplat/encoder/encoder_epipolar.py", line 130, in forward
    features = self.backbone(context)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xielangren/project/GGRt_official/ggrt/model/pixelsplat/encoder/backbone/backbone_dino.py", line 35, in forward
    resnet_features = self.resnet_backbone(context)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xielangren/project/GGRt_official/ggrt/model/pixelsplat/encoder/backbone/backbone_resnet.py", line 86, in forward
    features.append(self.projections[key](x))
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/xielangren/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 42.00 MiB. GPU 0 has a total capacty of 23.64 GiB of which 6.69 MiB is free. Including non-PyTorch memory, this process has 23.62 GiB memory in use. Of the allocated memory 21.28 GiB is allocated by PyTorch, and 1.85 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
How can it be solved, or what is your detailed training configuration?

**Comment by XLR-man** [comment]
And i tried to train the code on a single A100 GPU with 80GB, but i got the error:
```
Training pretrain_llff:   0%|                                                                                                                                           | 0/6000 [00:00<?, ?it/s][INFO] Resuming from latest checkpoint...
[WARNING] Checkpoint ./data/ibrnet/train/out/pretrain_llff/model.pth does not exist, training from scratch!
train set len 2785
Error executing job with overrides: []
Traceback (most recent call last):
  File "/data/lxx/code/GGRt_official/train_ggrt_stable.py", line 333, in train
    trainer.train()
  File "/data/lxx/code/GGRt_official/ggrt/base/trainer.py", line 224, in train
    self.train_iteration(data_batch=self.train_data)
  File "/data/lxx/code/GGRt_official/train_ggrt_stable.py", line 109, in train_iteration
    ret, data_gt = self.model.gaussian_model(batch, self.iteration)
  File "/home/lxx/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lxx/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/lxx/code/GGRt_official/ggrt/model/pixelsplat/pixelsplat.py", line 230, in forward
    output = self.decoder.forward(
  File "/data/lxx/code/GGRt_official/ggrt/model/pixelsplat/decoder/decoder_splatting_cuda.py", line 40, in forward
    color = render_cuda(
  File "/data/lxx/code/GGRt_official/ggrt/model/pixelsplat/decoder/cuda_splatting.py", line 119, in render_cuda
    image, radii, _ = rasterizer(
  File "/home/lxx/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/lxx/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/lxx/miniconda3/envs/ggrt/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 210, in forward
    return rasterize_gaussians(
  File "/home/lxx/miniconda3/envs/ggrt/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 32, in rasterize_gaussians
    return _RasterizeGaussians.apply(
  File "/home/lxx/miniconda3/envs/ggrt/lib/python3.10/site-packages/torch/autograd/function.py", line 539, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/lxx/miniconda3/envs/ggrt/lib/python3.10/site-packages/diff_gaussian_rasterization/__init__.py", line 92, in forward
    num_rendered, color, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

How can i solved it? I am looking for your reply

And it seems that you have an error in cuda_splatting.py:
```
        settings = GaussianRasterizationSettings(
            image_height=h,
            image_width=w,
            tanfovx=tan_fov_x[i].item(),
            tanfovy=tan_fov_y[i].item(),
            bg=background_color[i],
            scale_modifier=1.0,
            viewmatrix=view_matrix[i],
            projmatrix=full_projection[i],
            sh_degree=degree,
            campos=extrinsics[i, :3, 3],
            prefiltered=False,  # This matches the original usage.
            debug=False,
        )
```
you omit the debug=False in the settings, in function render_cuda
